package com.jiangzhichao.dao;

import com.jiangzhichao.entity.AdminDTO;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    int deleteByPrimaryKey(String ano);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    int insert(AdminDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    int insertSelective(AdminDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    AdminDTO selectByPrimaryKey(String ano);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    int updateByPrimaryKeySelective(AdminDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    int updateByPrimaryKey(AdminDTO record);
}