package com.jiangzhichao.dao;

import java.util.List;

import com.jiangzhichao.entity.CourseDTO;
import com.jiangzhichao.entity.CourseVO;
import com.jiangzhichao.entity.StudentDTO;

public interface CourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int deleteByPrimaryKey(String cno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int insert(CourseDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int insertSelective(CourseDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    CourseDTO selectByPrimaryKey(String cno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int updateByPrimaryKeySelective(CourseDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int updateByPrimaryKey(CourseDTO record);
    
    /**
     * 查询某教师所有授课
     */
    List<CourseDTO> selectByTno(String tno);
    
    /**
     * 查询某专业所有课程
     */
    List<CourseDTO> selectByDno(String dno);
    
    /**
     * 查询所有课程
     */
    List<CourseDTO> select();
    
    /**
     * 查询某教师本学期所有授课
     */
    List<CourseVO> selectByTnoAndTerm(String tno,String term);
    
    /**
     * 查询某教师过往学期所有授课
     */
    List<CourseVO> selectOldByTnoAndTerm(String tno,String term);
    
    /**
     * 查询本学期本专业所有可选课程
     */
    List<CourseVO> selectByDnoAndTerm(String dno,String term);
    
    /**
     * 查询某学生可选课程
     */
    List<CourseVO> selectBySno(StudentDTO student);
    
    /**
     * 查询某学生本学期课程信息和成绩
     */
    List<CourseVO> selectedBySno(String sno);
    
    /**
     * 查询某学生过往学期课程信息和成绩
     */
    List<CourseVO> selectedOldBySno(String sno);
    
    /**
     * 查询某学生总学分
     */
    Integer totalCredits(String sno);
}