package com.jiangzhichao.dao;

import java.util.List;

import com.jiangzhichao.entity.CourseDO;

public interface CourseDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int deleteByPrimaryKey(String cno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int insert(CourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int insertSelective(CourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    CourseDO selectByPrimaryKey(String cno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int updateByPrimaryKeySelective(CourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int updateByPrimaryKey(CourseDO record);
    
    /**
     * 查询某教师所有授课
     */
    List<CourseDO> selectByTno(String tno);
    
    /**
     * 查询某专业所有课程
     */
    List<CourseDO> selectByDno(String dno);
    
    /**
     * 查询所有课程
     */
    List<CourseDO> select();
}