package com.jiangzhichao.dao;

import java.util.List;

import com.jiangzhichao.entity.CourseDTO;

public interface CourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int deleteByPrimaryKey(String cno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int insert(CourseDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int insertSelective(CourseDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    CourseDTO selectByPrimaryKey(String cno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int updateByPrimaryKeySelective(CourseDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int updateByPrimaryKey(CourseDTO record);
    
    /**
     * 查询某教师所有授课
     */
    List<CourseDTO> selectByTno(String tno);
    
    /**
     * 查询某专业所有课程
     */
    List<CourseDTO> selectByDno(String dno);
    
    /**
     * 查询所有课程
     */
    List<CourseDTO> select();
}