package com.jiangzhichao.dao;

import java.util.List;

import com.jiangzhichao.entity.DepartmentDTO;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int deleteByPrimaryKey(String dno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int insert(DepartmentDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int insertSelective(DepartmentDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    DepartmentDTO selectByPrimaryKey(String dno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int updateByPrimaryKeySelective(DepartmentDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int updateByPrimaryKey(DepartmentDTO record);
    
    /**
     * 查询所有专业
     * 
     * @return 专业集合
     */
    List<DepartmentDTO> select();
}