package com.jiangzhichao.dao;

import com.jiangzhichao.entity.RoleDTO;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    int deleteByPrimaryKey(String roleno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    int insert(RoleDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    int insertSelective(RoleDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    RoleDTO selectByPrimaryKey(String roleno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    int updateByPrimaryKeySelective(RoleDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    int updateByPrimaryKey(RoleDTO record);
}