package com.jiangzhichao.dao;

import com.jiangzhichao.entity.RoleDO;

public interface RoleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    int deleteByPrimaryKey(String roleno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    int insert(RoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    int insertSelective(RoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    RoleDO selectByPrimaryKey(String roleno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    int updateByPrimaryKeySelective(RoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    int updateByPrimaryKey(RoleDO record);
}