package com.jiangzhichao.dao;

import com.jiangzhichao.entity.StuCourseDO;

public interface StuCourseDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stucourse
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int insert(StuCourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stucourse
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int insertSelective(StuCourseDO record);
}