package com.jiangzhichao.dao;

import com.jiangzhichao.entity.StudentDO;

public interface StudentDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int deleteByPrimaryKey(String sno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int insert(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int insertSelective(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    StudentDO selectByPrimaryKey(String sno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int updateByPrimaryKeySelective(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int updateByPrimaryKey(StudentDO record);
}