package com.jiangzhichao.dao;

import java.util.List;

import com.jiangzhichao.entity.StudentDTO;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int deleteByPrimaryKey(String sno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int insert(StudentDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int insertSelective(StudentDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    StudentDTO selectByPrimaryKey(String sno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int updateByPrimaryKeySelective(StudentDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    int updateByPrimaryKey(StudentDTO record);
    
    /**
     * 查询某专业下所有学生
     */
    List<StudentDTO> selectByDno(String dno);
    
    /**
     * 查询所有学生
     */
    List<StudentDTO> select();
}