package com.jiangzhichao.dao;

import java.util.List;

import com.jiangzhichao.entity.SubjectRoleDTOKey;

public interface SubjectRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjectrole
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    int deleteByPrimaryKey(SubjectRoleDTOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjectrole
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    int insert(SubjectRoleDTOKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjectrole
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    int insertSelective(SubjectRoleDTOKey record);
    
    /**
     * 删除角色
     * @param no
     * @return
     */
    int deleteByNo(String no);
    
    /**
     * 查询角色
     */
    List<SubjectRoleDTOKey> selectByNo(String no); 
}