package com.jiangzhichao.dao;

import java.util.List;

import com.jiangzhichao.entity.SubjectRoleDOKey;

public interface SubjectRoleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjectrole
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    int deleteByPrimaryKey(SubjectRoleDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjectrole
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    int insert(SubjectRoleDOKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjectrole
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    int insertSelective(SubjectRoleDOKey record);
    
    /**
     * 删除角色
     * @param no
     * @return
     */
    int deleteByNo(String no);
    
    /**
     * 查询角色
     */
    List<SubjectRoleDOKey> selectByNo(String no); 
}