package com.jiangzhichao.dao;

import java.util.List;

import com.jiangzhichao.entity.TeacherDO;

public interface TeacherDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    int deleteByPrimaryKey(String tno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    int insert(TeacherDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    int insertSelective(TeacherDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    TeacherDO selectByPrimaryKey(String tno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    int updateByPrimaryKeySelective(TeacherDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    int updateByPrimaryKey(TeacherDO record);
    
    /**
     * 查询所有教师信息
     * 
     * @return 教师信息集合
     */
    List<TeacherDO> select();
}