package com.jiangzhichao.dao;

import java.util.List;

import com.jiangzhichao.entity.TeacherDTO;

public interface TeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    int deleteByPrimaryKey(String tno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    int insert(TeacherDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    int insertSelective(TeacherDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    TeacherDTO selectByPrimaryKey(String tno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    int updateByPrimaryKeySelective(TeacherDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    int updateByPrimaryKey(TeacherDTO record);
    
    /**
     * 查询所有教师信息
     * 
     * @return 教师信息集合
     */
    List<TeacherDTO> select();
}