package com.jiangzhichao.entity;

public class AdminDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.ano
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    private String ano;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.ausername
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    private String ausername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.apassword
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    private String apassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.ano
     *
     * @return the value of admin.ano
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    public String getAno() {
        return ano;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.ano
     *
     * @param ano the value for admin.ano
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    public void setAno(String ano) {
        this.ano = ano == null ? null : ano.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.ausername
     *
     * @return the value of admin.ausername
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    public String getAusername() {
        return ausername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.ausername
     *
     * @param ausername the value for admin.ausername
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    public void setAusername(String ausername) {
        this.ausername = ausername == null ? null : ausername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.apassword
     *
     * @return the value of admin.apassword
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    public String getApassword() {
        return apassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.apassword
     *
     * @param apassword the value for admin.apassword
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    public void setApassword(String apassword) {
        this.apassword = apassword == null ? null : apassword.trim();
    }
}