package com.jiangzhichao.entity;

public class CourseDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cno
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    private String cno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cname
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.credit
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    private Integer credit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.dno
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    private String dno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.currentnum
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    private Integer currentnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.maxnum
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    private Integer maxnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cintroduce
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    private String cintroduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.tno
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    private String tno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cterm
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    private String cterm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cno
     *
     * @return the value of course.cno
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public String getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cno
     *
     * @param cno the value for course.cno
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public void setCno(String cno) {
        this.cno = cno == null ? null : cno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cname
     *
     * @return the value of course.cname
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cname
     *
     * @param cname the value for course.cname
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.credit
     *
     * @return the value of course.credit
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public Integer getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.credit
     *
     * @param credit the value for course.credit
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.dno
     *
     * @return the value of course.dno
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public String getDno() {
        return dno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.dno
     *
     * @param dno the value for course.dno
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public void setDno(String dno) {
        this.dno = dno == null ? null : dno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.currentnum
     *
     * @return the value of course.currentnum
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public Integer getCurrentnum() {
        return currentnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.currentnum
     *
     * @param currentnum the value for course.currentnum
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public void setCurrentnum(Integer currentnum) {
        this.currentnum = currentnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.maxnum
     *
     * @return the value of course.maxnum
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public Integer getMaxnum() {
        return maxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.maxnum
     *
     * @param maxnum the value for course.maxnum
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public void setMaxnum(Integer maxnum) {
        this.maxnum = maxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cintroduce
     *
     * @return the value of course.cintroduce
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public String getCintroduce() {
        return cintroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cintroduce
     *
     * @param cintroduce the value for course.cintroduce
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public void setCintroduce(String cintroduce) {
        this.cintroduce = cintroduce == null ? null : cintroduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.tno
     *
     * @return the value of course.tno
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public String getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.tno
     *
     * @param tno the value for course.tno
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public void setTno(String tno) {
        this.tno = tno == null ? null : tno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cterm
     *
     * @return the value of course.cterm
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public String getCterm() {
        return cterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cterm
     *
     * @param cterm the value for course.cterm
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public void setCterm(String cterm) {
        this.cterm = cterm == null ? null : cterm.trim();
    }
}