package com.jiangzhichao.entity;

public class DepartmentDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.dno
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    private String dno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.dname
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    private String dname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.dintroduce
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    private String dintroduce;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.dno
     *
     * @return the value of department.dno
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public String getDno() {
        return dno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.dno
     *
     * @param dno the value for department.dno
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public void setDno(String dno) {
        this.dno = dno == null ? null : dno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.dname
     *
     * @return the value of department.dname
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.dname
     *
     * @param dname the value for department.dname
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public void setDname(String dname) {
        this.dname = dname == null ? null : dname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.dintroduce
     *
     * @return the value of department.dintroduce
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public String getDintroduce() {
        return dintroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.dintroduce
     *
     * @param dintroduce the value for department.dintroduce
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public void setDintroduce(String dintroduce) {
        this.dintroduce = dintroduce == null ? null : dintroduce.trim();
    }
}