package com.jiangzhichao.entity;

/**
 * 角色Bean
 * 
 * @author BornToWin
 *
 */
public class RoleDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.roleno
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    private String roleno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.rolename
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    private String rolename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.roleintroduce
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    private String roleintroduce;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.roleno
     *
     * @return the value of role.roleno
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    public String getRoleno() {
        return roleno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.roleno
     *
     * @param roleno the value for role.roleno
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    public void setRoleno(String roleno) {
        this.roleno = roleno == null ? null : roleno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.rolename
     *
     * @return the value of role.rolename
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.rolename
     *
     * @param rolename the value for role.rolename
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.roleintroduce
     *
     * @return the value of role.roleintroduce
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    public String getRoleintroduce() {
        return roleintroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.roleintroduce
     *
     * @param roleintroduce the value for role.roleintroduce
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    public void setRoleintroduce(String roleintroduce) {
        this.roleintroduce = roleintroduce == null ? null : roleintroduce.trim();
    }

	@Override
	public String toString() {
		return "RoleDTO [roleno=" + roleno + ", rolename=" + rolename + ", roleintroduce=" + roleintroduce + "]";
	}
    
    
}