package com.jiangzhichao.entity;

public class StuCourseDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stucourse.sno
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    private String sno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stucourse.cno
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    private String cno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stucourse.score
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stucourse.sno
     *
     * @return the value of stucourse.sno
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public String getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stucourse.sno
     *
     * @param sno the value for stucourse.sno
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public void setSno(String sno) {
        this.sno = sno == null ? null : sno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stucourse.cno
     *
     * @return the value of stucourse.cno
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public String getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stucourse.cno
     *
     * @param cno the value for stucourse.cno
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public void setCno(String cno) {
        this.cno = cno == null ? null : cno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stucourse.score
     *
     * @return the value of stucourse.score
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stucourse.score
     *
     * @param score the value for stucourse.score
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}