package com.jiangzhichao.entity;

public class StudentDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sno
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    private String sno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sname
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.spassword
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    private String spassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sterm
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    private String sterm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.dno
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    private String dno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.ssex
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    private String ssex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.idcard
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    private String idcard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sno
     *
     * @return the value of student.sno
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public String getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sno
     *
     * @param sno the value for student.sno
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public void setSno(String sno) {
        this.sno = sno == null ? null : sno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sname
     *
     * @return the value of student.sname
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sname
     *
     * @param sname the value for student.sname
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.spassword
     *
     * @return the value of student.spassword
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public String getSpassword() {
        return spassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.spassword
     *
     * @param spassword the value for student.spassword
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public void setSpassword(String spassword) {
        this.spassword = spassword == null ? null : spassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sterm
     *
     * @return the value of student.sterm
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public String getSterm() {
        return sterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sterm
     *
     * @param sterm the value for student.sterm
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public void setSterm(String sterm) {
        this.sterm = sterm == null ? null : sterm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.dno
     *
     * @return the value of student.dno
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public String getDno() {
        return dno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.dno
     *
     * @param dno the value for student.dno
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public void setDno(String dno) {
        this.dno = dno == null ? null : dno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.ssex
     *
     * @return the value of student.ssex
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public String getSsex() {
        return ssex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.ssex
     *
     * @param ssex the value for student.ssex
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public void setSsex(String ssex) {
        this.ssex = ssex == null ? null : ssex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.idcard
     *
     * @return the value of student.idcard
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.idcard
     *
     * @param idcard the value for student.idcard
     *
     * @mbg.generated Wed Apr 18 20:00:37 CST 2018
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }
}