package com.jiangzhichao.entity;

/**
 * 用户对应角色Bean
 * 
 * @author BornToWin
 *
 */
public class SubjectRoleDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subjectrole.no
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subjectrole.roleno
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    private String roleno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subjectrole.no
     *
     * @return the value of subjectrole.no
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subjectrole.no
     *
     * @param no the value for subjectrole.no
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subjectrole.roleno
     *
     * @return the value of subjectrole.roleno
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    public String getRoleno() {
        return roleno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subjectrole.roleno
     *
     * @param roleno the value for subjectrole.roleno
     *
     * @mbg.generated Sat Apr 21 13:10:43 CST 2018
     */
    public void setRoleno(String roleno) {
        this.roleno = roleno == null ? null : roleno.trim();
    }

	@Override
	public String toString() {
		return "SubjectRoleDTOKey [no=" + no + ", roleno=" + roleno + "]";
	}
    
}