package com.jiangzhichao.entity;

import org.jeecgframework.poi.excel.annotation.Excel;
import org.jeecgframework.poi.excel.annotation.ExcelTarget;

@ExcelTarget("Teacher")
public class TeacherDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tno
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
	@Excel(name = "工号")
    private String tno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tname
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
	@Excel(name = "名称")
    private String tname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tpassword
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
	@Excel(name = "密码")
    private String tpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.ttitle
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
	@Excel(name = "职称")
    private String ttitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tsex
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
	@Excel(name = "性别")
    private String tsex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tno
     *
     * @return the value of teacher.tno
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    public String getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tno
     *
     * @param tno the value for teacher.tno
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    public void setTno(String tno) {
        this.tno = tno == null ? null : tno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tname
     *
     * @return the value of teacher.tname
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tname
     *
     * @param tname the value for teacher.tname
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tpassword
     *
     * @return the value of teacher.tpassword
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    public String getTpassword() {
        return tpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tpassword
     *
     * @param tpassword the value for teacher.tpassword
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    public void setTpassword(String tpassword) {
        this.tpassword = tpassword == null ? null : tpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.ttitle
     *
     * @return the value of teacher.ttitle
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    public String getTtitle() {
        return ttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.ttitle
     *
     * @param ttitle the value for teacher.ttitle
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    public void setTtitle(String ttitle) {
        this.ttitle = ttitle == null ? null : ttitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tsex
     *
     * @return the value of teacher.tsex
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    public String getTsex() {
        return tsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tsex
     *
     * @param tsex the value for teacher.tsex
     *
     * @mbg.generated Tue Apr 17 19:54:22 CST 2018
     */
    public void setTsex(String tsex) {
        this.tsex = tsex == null ? null : tsex.trim();
    }

	@Override
	public String toString() {
		return "TeacherDO [tno=" + tno + ", tname=" + tname + ", tpassword=" + tpassword + ", ttitle=" + ttitle
				+ ", tsex=" + tsex + "]";
	}
}